### ISSUE TITLE
ARTwarp performance improvements 

### ISSUE THREAD

**Issue by RohanK22** [vmjanik/artwarp#4]
Profile the MATLAB code and check and resolve any bottlenecks in the code.

**Comment by alex-konovalov** [comment]
@douggillespie had some suggestions in a recent email where to look - could we have them copied and pasted here please?

**Comment by alex-konovalov** [comment]
This will be addressed by #9 by @RohanK22

**Comment by alex-konovalov** [comment]
Closed by #9.
